### PR TITLE
Context menu doesn't go away when clicking in whitespace

### LINKED ISSUE #129: When context menu is open, [left|right] clicking anywhere else should close it
Just like when you right-click on say, your desktop, the context menu will go away (or move) when you left-click or right-click elsewhere.

**To reproduce:**
1. Make a single request
2. Right click on the request
3. Left click in the whitespace before
The context menu is still there, but it should've gone away after `3.`

### PR DESCRIPTION
**Pull request by mitchhentges**
Fixes #129

### CODE REVIEW

File: src/component/main-content/main-content.js [hunk 1]
```diff
@@ -8,16 +9,13 @@ const {func, object, arrayOf, shape, array} = React.PropTypes;
 
 export default class MainContent extends React.Component {
 
-  constructor() {
-    super();
-  }
-
-  componentWillMount() {
-    this.setState({
+  constructor(props) {
```
Comment (mitchhentges) [inline src/component/main-content/main-content.js]: Move state setting to constructor, as laid out here: https://facebook.github.io/react/docs/reusable-components.html#es6-classes

File: src/component/main-content/main-content.js [hunk 2]
```diff
@@ -78,8 +81,9 @@ export default class MainContent extends React.Component {
         request={activeRequest}
         setActiveRequest={this.setActiveRequest.bind(this)} />;
     }
+    const clickHandler = this.onClick.bind(this);
```
Comment (tomitm) [inline src/component/main-content/main-content.js]: You should probably just move this up into the constructor.
